<h1>Lookup</h1>
<hr>
<?php if ($this->list) : ?>
    <pre>
    <?php printf("%12s : %20s : %20s : %2s : %12s\n", '      First Name', 'Last Name', 'City', ' ', 'Post Code'); ?>
    <?php printf("%12s : %20s : %20s : %2s : %12s\n", '----------------', '---------', '----', '--', '---------'); ?>
    <?php foreach ($this->list as $value) : ?>
    <?php   $item = (object) $value; ?>
    <?php   printf("%12s : %20s : %20s : %2s : %12s\n", $item->first_name, $item->last_name, substr($item->city,0,20), $item->country, $item->postalCode); ?>
    <?php endforeach; ?>
    </pre>
<?php else : ?>
No items on the list
<?php endif; ?>
